# Generated by Django 4.2.1 on 2023-05-22 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseBTC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('time_end', models.DateTimeField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('b', models.IntegerField(null=True)),
                ('c', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseETH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('time_end', models.DateTimeField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('b', models.IntegerField(null=True)),
                ('c', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseUSDT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('time_end', models.DateTimeField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('b', models.IntegerField(null=True)),
                ('c', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetPhaseETH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a', models.IntegerField(default=-1)),
                ('b', models.IntegerField(default=-1)),
                ('c', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SetPhaseUSDT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a', models.IntegerField(default=-1)),
                ('b', models.IntegerField(default=-1)),
                ('c', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='TradeBTC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('trade_value', models.IntegerField()),
                ('trade_type', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('room_type_trade', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('result', models.BooleanField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeBTC', to='ModuleApp.phasebtc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeBTC', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeETH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('trade_value', models.IntegerField()),
                ('trade_type', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('room_type_trade', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('result', models.BooleanField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeETH', to='ModuleApp.phaseeth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeETH', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeUSDT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('trade_value', models.IntegerField()),
                ('trade_type', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('room_type_trade', models.IntegerField(choices=[(1, 'Long'), (2, 'Short'), (3, 'Single'), (4, 'Double'), (5, 'LS'), (6, 'SS'), (7, 'LD'), (8, 'SD'), (9, 'Maximum'), (10, 'Minimum')])),
                ('result', models.BooleanField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeUSDT', to='ModuleApp.phaseusdt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeUSDT', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='SetPhase',
            new_name='SetPhaseBTC',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
