# Generated by Django 4.2.1 on 2023-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0003_remove_phasebtc_time_end_remove_phaseeth_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmoney',
            name='detail',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputmoney',
            name='value_control',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inputmoney',
            name='value_real',
            field=models.IntegerField(null=True),
        ),
    ]
