# Generated by Django 4.2.1 on 2023-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0004_inputmoney_detail_inputmoney_value_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmoney',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Fail', 'Fail')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='outputmoney',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Fail', 'Fail')], default='Pending', max_length=20),
        ),
    ]
