# Generated by Django 4.0.1 on 2023-06-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0007_alter_tradeusdt_room_type_trade_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeusdt',
            name='trade_type',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('Single', 'Single'), ('Double', 'Double'), ('LS', 'LS'), ('SS', 'SS'), ('LD', 'LD'), ('SD', 'SD'), ('Maximum', 'Maximum'), ('Minimum', 'Minimum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Admin'), (2, 'Staff'), (3, 'Guest')], default=0),
        ),
        migrations.CreateModel(
            name='GuestCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_login', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_check', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
