# Generated by Django 4.0.1 on 2023-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0008_alter_tradeusdt_trade_type_alter_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseusdt',
            name='phase_check',
            field=models.BooleanField(default=False),
        ),
    ]
