# Generated by Django 4.0.1 on 2023-06-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0009_phaseusdt_phase_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmoney',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
