# Generated by Django 4.0.1 on 2023-06-22 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleApp', '0011_alter_tradeusdt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcheck',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
